backend:
  name: github
  repo: wolfrobert35/jnjartgroup
  branch: master # Branch to update (optional; defaults to master)

media_folder: 'static/img' # this is where netlify cms places images.
public_folder: '/img' # this is where gatsby places images

collections:

  - name: 'gallery'
    label: 'Gallery'
    folder: 'src/pages/galleries'
    create: true
    slug: '{{slug}}'
    fields:
      - {name: kind, widget: hidden, default: 'gallery'}
      - {label: 'Template', name: 'templateKey', widget: 'hidden', default: gallery }
      - {label: 'Path', name: 'path', widget: 'string', pattern: ['^\/[a-z0-9\-]+$', 'Must begin with "/" and may only consist of lowercase letters (except umlauts), numbers and "-"']}
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Název', name: 'nazev', widget: 'string'}
      - {label: 'Description', name: 'description', widget: 'text'}
      - {label: 'Popis', name: 'popis', widget: 'text'}
      - {name: order, label: 'Pořadí', widget: number, default: 0}
      - name: images
        label: Gallery
        widget: gallery
        required: true
        fields:
          - {name: image, label: Image, widget: image, class: 'gallery'}
          - {name: price, label: Cena, widget: text}

  - name: artists
    label: Artists
    folder: 'src/pages/artists'
    slug: "/artists/{{slug}}"
    create: true
    meta:
      - {label: "SEO Description", name: "description", widget: "text"}
    fields:
      - {name: kind, widget: hidden, default: 'artist'}
      - {label: 'Template', name: 'templateKey', widget: 'hidden', default: artist }
      - {label: "Name", name: "title", widget: "string", tagname: "h1"}
      - {label: 'Path', name: 'path', widget: 'string', pattern: ['^\/[a-z0-9\-]+$', 'Must begin with "/" and may only consist of lowercase letters (except umlauts), numbers and "-"']}
      - {label: "Type", name: "type", widget: "select", options: ["hair", "makeup", "stylist", "grooming", "manicurist", "color"]}
      - {name: order, label: Position, widget: number, default: 0}
      - {label: "Instagram handle", name: "instagram_handle", widget: "string", tagname: "p", required: false}
      - {label: "Instagram API key", name: "instagram_key", widget: "string", tagname: "p", required: false}
      - name: portfolios
        label: Portfolios
        widget: list
        optional: true
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
          - name: gallery
            label: Gallery
            widget: gallery
            required: true
            fields:
              - {name: image, label: Image, widget: image, class: 'gallery'}
              - {name: 'fullscreen', label: 'Fullscreen', widget: 'boolean', default: false }
              - {name: 'focalX', label: 'Focal X', widget: 'number', default: 0, valueType: 'int', min: 0, max: 100}
              - {name: 'focalY', label: 'Focal Y', widget: 'number', default: 0, valueType: 'int', min: 0, max: 100}
      - name: videos
        label: Videos
        widget: list
        optional: true
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'URL', name: 'video_url', widget: 'string'}
      - {label: "Biography Text", name: "body", widget: "markdown"}
      - {label: "Portrait Image", name: "image", widget: "image", required: false, tagname: ""}
